# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: Home
site_url: https://github.com/bcataldo3/plantilla_curso_python
site_author: Benjamin Cataldo
site_description: Curso Machine Learning No Supervisado

# Repository
repo_name: bcataldo3/UTSM_Unspervised_ML
repo_url: https://github.com/bcataldo3/UTSM_Unspervised_ML
edit_uri: ''


# Markdown extensions
markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed

# Extra javascript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Theme
theme:
  name: material
  language: es
  logo: images/logo.bmp
  favicon: docs/images/logo_python.svg
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bcataldo3




# Plugins
plugins:
  - mkdocs-jupyter:
      kernel_name: python3
  - search

# TOC
nav:
    - Home: index.md
    - Introducción:  
      - Clase_01 - Modelos No Supervisados - Introduccion.ipynb
    - Modelos Conglomerados:
      - Clase_02 - Modelos Conglomerados - Introduccion.ipynb
      - Clase_03 - Modelo K-Medias.ipynb
      - Clase_04 - Modelo K-Medias Caso Estudio.ipynb
      - Clase_05 - Modelo K-Medias Metricas Evaluacion.ipynb
      - Clase_06 - Modelos Jerarquicos.ipynb
      - Clase_07 - Modelos Jerárquicos - Caso Estudio.ipynb
    - Reducción de Dimensionalidad:
      - Clase_08 - Reduccion Dimensionalidad y Analisis Componentes.ipynb
      - Clase_09 - PCA - Caso Estudio.ipynb
    - Detección de Anomalías:
      - Clase_10 - Detección de Anomalias - Introducción.ipynb
      - Clase_11 - Deteccion de Anomalias - Estimacion Densidad del Kernel.ipynb
